kind: pipeline
name: drone
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
  - name: npm-install
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm install

  - name: build-dist
    image: node:10
    commands:
      - npm run build:prod

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache



  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      registry: swr.cn-north-1.myhuaweicloud.com
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/mass-page
      auto_tag: true

  - name: up
    image: alpine
    commands:
      #        - docker stack deploy -c docker-compose.yml mass-page
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/mass-page mass-page_mass-page --with-registry-auth


volumes:
  - name: cache
    host:
      path: /tmp/cache
