version: "3"
networks:
  default:
    external:
      name: swarm-net
services:
  mass-page:
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/mass-page
    deploy:
      labels:
        - traefik.http.routers.mass-page.rule=Host(`mass.zhihuizhan.net`)
        - traefik.http.middlewares.mass-page-http.redirectscheme.scheme=https_redirect

        - traefik.http.services.mass-page.loadbalancer.server.port=80
        - traefik.http.routers.mass-page.rule=Host(`mass.zhihuizhan.net`)
        - traefik.http.routers.mass-page.tls.certresolver=mytlschallenge

