version: "3"
networks:
  default:
    external:
      name: default-network
services:
  mass-page:
    container_name: drone-mass-page
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/mass-page
    labels:
      - traefik.http.routers.mass-page.rule=Host(`mass.zhihuizhan.net`)
      - traefik.http.routers.mass-page.tls.certresolver=mytlschallenge

